name = "analyst"
compatibility_date = "2024-02-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "analyst"
database_id = "e5c4f6d2-3161-4200-b516-620dfab59ce8"
migrations_dir = 'migrations'


[[r2_buckets]]
binding = 'R2_STORAGE'
bucket_name = 'analyst'

[vars]
BACKEND_API_URL = "http://poc1.roleai.chat"